// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oifqhuxjmqqgslnjhazx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pZnFodXhqbXFxZ3NsbmpoYXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNzk1MjUsImV4cCI6MjA2Mjc1NTUyNX0.w9iuU5ToVx7uPU5JjjFOkL0Tu513FRdiepxTWeD3EKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);